"""
Running Log – Event Editor
Adds/edits runs and personal bests.
Saves individual JSON files → data/runs/ or data/pbs/
Regenerates data/data.js for running-log.html.
"""

import json
import os
import shutil
import tkinter as tk
from tkinter import filedialog, messagebox, ttk
from datetime import date, datetime
from pathlib import Path

BASE_DIR      = Path(__file__).parent
DATA_DIR      = BASE_DIR / "data"
RUNS_DIR      = DATA_DIR / "runs"
PBS_DIR       = DATA_DIR / "pbs"
PHOTOS_DIR    = DATA_DIR / "photos"
DATA_JS       = DATA_DIR / "data.js"
SNEAKERS_FILE = DATA_DIR / "sneakers.json"

for d in (RUNS_DIR, PBS_DIR, PHOTOS_DIR):
    d.mkdir(parents=True, exist_ok=True)

IMG_EXTS = {".jpg", ".jpeg", ".png", ".gif", ".webp", ".avif"}

# ── JSON helpers ──────────────────────────────────────────────────────────────

def load_all_runs():
    runs = []
    for f in sorted(RUNS_DIR.glob("*.json")):
        try:
            runs.append(json.loads(f.read_text("utf-8")))
        except Exception:
            pass
    return runs


def load_all_pbs():
    pbs = []
    for f in sorted(PBS_DIR.glob("*.json")):
        try:
            pbs.append(json.loads(f.read_text("utf-8")))
        except Exception:
            pass
    return pbs


def run_filename(run: dict) -> Path:
    return RUNS_DIR / f"{run['date']}.json"


def pb_filename(pb: dict) -> Path:
    slug = pb["distance"].lower().replace(" ", "_").replace("/", "")
    return PBS_DIR / f"{slug}.json"


def save_run(run: dict):
    path = run_filename(run)
    path.write_text(json.dumps(run, ensure_ascii=False, indent=2), "utf-8")


def save_pb(pb: dict):
    path = pb_filename(pb)
    path.write_text(json.dumps(pb, ensure_ascii=False, indent=2), "utf-8")


def rebuild_data_js():
    runs = load_all_runs()
    pbs  = load_all_pbs()
    js   = (
        "// Auto-generated by add_new_event.py — do not edit manually\n"
        f"const RUNS_DATA = {json.dumps(runs, ensure_ascii=False, indent=2)};\n\n"
        f"const PBS_DATA = {json.dumps(pbs,  ensure_ascii=False, indent=2)};\n"
    )
    DATA_JS.write_text(js, "utf-8")


def copy_photos(src_folder: str, event_key: str) -> list[str]:
    """Copy images from src_folder to data/photos/<event_key>/; return relative paths."""
    if not src_folder:
        return []
    src = Path(src_folder)
    if not src.is_dir():
        return []
    dest = PHOTOS_DIR / event_key
    dest.mkdir(parents=True, exist_ok=True)
    paths = []
    for f in sorted(src.iterdir()):
        if f.suffix.lower() in IMG_EXTS:
            target = dest / f.name
            shutil.copy2(f, target)
            rel = target.relative_to(BASE_DIR).as_posix()
            paths.append(rel)
    return paths

# ── Sneakers list ────────────────────────────────────────────────────────────

def load_sneakers() -> list:
    if SNEAKERS_FILE.exists():
        return json.loads(SNEAKERS_FILE.read_text("utf-8"))
    return []


def save_sneakers(names: list):
    SNEAKERS_FILE.write_text(json.dumps(names, ensure_ascii=False, indent=2), "utf-8")


def ensure_sneaker(name: str):
    if not name:
        return
    names = load_sneakers()
    if name not in names:
        names.append(name)
        save_sneakers(names)


def init_sneakers_file():
    if SNEAKERS_FILE.exists():
        return
    names = []
    for r in load_all_runs() + load_all_pbs():
        s = r.get("sneakers", "")
        if s and s not in names:
            names.append(s)
    save_sneakers(names)


# ── GUI ───────────────────────────────────────────────────────────────────────

PAD = {"padx": 8, "pady": 5}
ENTRY_W = 30


def labeled_entry(parent, label, row, default=""):
    tk.Label(parent, text=label, anchor="e", width=16).grid(row=row, column=0, sticky="e", **PAD)
    var = tk.StringVar(value=default)
    tk.Entry(parent, textvariable=var, width=ENTRY_W).grid(row=row, column=1, sticky="ew", **PAD)
    return var


class RunTab(tk.Frame):
    def __init__(self, master, app):
        super().__init__(master)
        self.app = app
        self.columnconfigure(1, weight=1)

        today = date.today().isoformat()

        self.v_date       = labeled_entry(self, "Date (YYYY-MM-DD)", 0, today)
        self.v_location   = labeled_entry(self, "Location", 1)
        self.v_dist       = labeled_entry(self, "Distance (km)", 2)
        self.v_total_time = labeled_entry(self, "Total time (H:MM:SS)", 3)
        self.v_hr_avg      = labeled_entry(self, "Avg HR (bpm)", 4)
        self.v_hr_max      = labeled_entry(self, "Max HR (bpm)", 5)
        self.v_elevation   = labeled_entry(self, "Elevation (m)", 6, "0")

        tk.Label(self, text="Sneakers", anchor="e", width=16).grid(row=7, column=0, sticky="e", **PAD)
        self.v_sneakers = tk.StringVar()
        self.cb_sneakers_run = ttk.Combobox(self, textvariable=self.v_sneakers, width=ENTRY_W - 2)
        self.cb_sneakers_run['values'] = load_sneakers()
        self.cb_sneakers_run.grid(row=7, column=1, sticky="ew", **PAD)

        # Photos folder row
        tk.Label(self, text="Photos folder", anchor="e", width=16).grid(row=8, column=0, sticky="e", **PAD)
        ph_frame = tk.Frame(self)
        ph_frame.grid(row=8, column=1, sticky="ew", **PAD)
        ph_frame.columnconfigure(0, weight=1)
        self.v_photos = tk.StringVar()
        tk.Entry(ph_frame, textvariable=self.v_photos).grid(row=0, column=0, sticky="ew")
        tk.Button(ph_frame, text="Browse…", command=self._browse).grid(row=0, column=1, padx=(6, 0))

        tk.Button(self, text="💾  Save Run", command=self._save,
                  bg="#e8521b", fg="white", font=("", 11, "bold"),
                  padx=18, pady=6).grid(row=9, column=0, columnspan=2, pady=16)

    def _browse(self):
        folder = filedialog.askdirectory(title="Select photos folder")
        if folder:
            self.v_photos.set(folder)

    def _save(self):
        try:
            dist = float(self.v_dist.get().replace(",", "."))
        except ValueError:
            messagebox.showerror("Error", "Distance must be a number.")
            return

        run = {
            "date":        self.v_date.get().strip(),
            "location":    self.v_location.get().strip(),
            "distance_km": dist,
            "total_time":  self.v_total_time.get().strip(),
            "hr_avg":      int(self.v_hr_avg.get() or 0),
            "hr_max":      int(self.v_hr_max.get() or 0),
            "elevation":   int(self.v_elevation.get() or 0),
            "sneakers":    self.v_sneakers.get().strip(),
            "photos":      [],
        }

        event_key = run["date"]
        run["photos"] = copy_photos(self.v_photos.get(), event_key)

        ensure_sneaker(run["sneakers"])
        save_run(run)
        rebuild_data_js()
        self.cb_sneakers_run['values'] = load_sneakers()
        messagebox.showinfo("Saved", f"Run on {run['date']} saved!\n{len(run['photos'])} photo(s) copied.")
        self.app.refresh_lists()


class PBTab(tk.Frame):
    def __init__(self, master, app):
        super().__init__(master)
        self.app = app
        self.columnconfigure(1, weight=1)

        today = date.today().isoformat()

        self.v_distance    = labeled_entry(self, "Distance label", 0, "5 km")
        self.v_distance_km = labeled_entry(self, "Distance (km)", 1)
        self.v_total_time  = labeled_entry(self, "Total time (H:MM:SS)", 2)
        self.v_date       = labeled_entry(self, "Date (YYYY-MM-DD)", 3, today)
        self.v_location   = labeled_entry(self, "Location", 4)
        self.v_hr_avg     = labeled_entry(self, "Avg HR (bpm)", 5)
        self.v_hr_max     = labeled_entry(self, "Max HR (bpm)", 6)

        tk.Label(self, text="Sneakers", anchor="e", width=16).grid(row=7, column=0, sticky="e", **PAD)
        self.v_sneakers = tk.StringVar()
        self.cb_sneakers_pb = ttk.Combobox(self, textvariable=self.v_sneakers, width=ENTRY_W - 2)
        self.cb_sneakers_pb['values'] = load_sneakers()
        self.cb_sneakers_pb.grid(row=7, column=1, sticky="ew", **PAD)

        tk.Label(self, text="Photos folder", anchor="e", width=16).grid(row=8, column=0, sticky="e", **PAD)
        ph_frame = tk.Frame(self)
        ph_frame.grid(row=8, column=1, sticky="ew", **PAD)
        ph_frame.columnconfigure(0, weight=1)
        self.v_photos = tk.StringVar()
        tk.Entry(ph_frame, textvariable=self.v_photos).grid(row=0, column=0, sticky="ew")
        tk.Button(ph_frame, text="Browse…", command=self._browse).grid(row=0, column=1, padx=(6, 0))

        tk.Label(self, text="Previous records", anchor="e", width=16).grid(row=9, column=0, sticky="ne", **PAD)
        self.prev_text = tk.Text(self, height=4, width=ENTRY_W)
        self.prev_text.grid(row=9, column=1, sticky="ew", **PAD)
        tk.Label(self, text="Format: time|date|location\none per line",
                 fg="grey", font=("", 8)).grid(row=10, column=1, sticky="w", padx=8)

        tk.Button(self, text="💾  Save Personal Best", command=self._save,
                  bg="#e8521b", fg="white", font=("", 11, "bold"),
                  padx=18, pady=6).grid(row=11, column=0, columnspan=2, pady=16)

    def _browse(self):
        folder = filedialog.askdirectory(title="Select photos folder")
        if folder:
            self.v_photos.set(folder)

    def _parse_previous(self):
        records = []
        for line in self.prev_text.get("1.0", "end").strip().splitlines():
            parts = [p.strip() for p in line.split("|")]
            if len(parts) == 3:
                records.append({"time": parts[0], "date": parts[1], "location": parts[2]})
        return records

    def _save(self):
        try:
            dist_km = float(self.v_distance_km.get().replace(",", "."))
        except ValueError:
            messagebox.showerror("Error", "Distance (km) must be a number.")
            return

        pb = {
            "distance":         self.v_distance.get().strip(),
            "distance_km":      dist_km,
            "total_time":       self.v_total_time.get().strip(),
            "date":             self.v_date.get().strip(),
            "location":         self.v_location.get().strip(),
            "hr_avg":           int(self.v_hr_avg.get() or 0),
            "hr_max":           int(self.v_hr_max.get() or 0),
            "sneakers":         self.v_sneakers.get().strip(),
            "photos":           [],
            "previous_records": self._parse_previous(),
        }

        event_key = "pb_" + pb["distance"].lower().replace(" ", "_").replace("/", "")
        pb["photos"] = copy_photos(self.v_photos.get(), event_key)

        ensure_sneaker(pb["sneakers"])
        save_pb(pb)
        rebuild_data_js()
        self.cb_sneakers_pb['values'] = load_sneakers()
        messagebox.showinfo("Saved", f"Personal Best '{pb['distance']}' saved!\n{len(pb['photos'])} photo(s) copied.")
        self.app.refresh_lists()


class ViewTab(tk.Frame):
    """Simple read-only list of existing events."""

    def __init__(self, master, app):
        super().__init__(master)
        self.app = app
        self.columnconfigure(0, weight=1)
        self.rowconfigure(1, weight=1)

        tk.Label(self, text="Existing events (read-only)", font=("", 10, "bold")).grid(
            row=0, column=0, sticky="w", padx=8, pady=(8, 4))

        self.text = tk.Text(self, state="disabled", wrap="none", font=("Courier", 9))
        sb = tk.Scrollbar(self, command=self.text.yview)
        self.text.configure(yscrollcommand=sb.set)
        self.text.grid(row=1, column=0, sticky="nsew", padx=(8, 0), pady=4)
        sb.grid(row=1, column=1, sticky="ns", pady=4)

        tk.Button(self, text="↺  Refresh", command=self.refresh).grid(
            row=2, column=0, columnspan=2, pady=8)

        self.refresh()

    def refresh(self):
        lines = ["═══ RUNS ═══"]
        for r in sorted(load_all_runs(), key=lambda x: x["date"], reverse=True):
            lines.append(f"  {r['date']}  {r['location']}  {r['distance_km']} km  {r['total_time']}")
        lines += ["", "═══ PERSONAL BESTS ═══"]
        for pb in load_all_pbs():
            lines.append(f"  {pb['distance']}  {pb['total_time']}  {pb['date']}  {pb['location']}")
        content = "\n".join(lines)

        self.text.configure(state="normal")
        self.text.delete("1.0", "end")
        self.text.insert("end", content)
        self.text.configure(state="disabled")


class App(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title("Running Log – Add Event")
        self.resizable(True, True)
        self.minsize(520, 480)

        nb = ttk.Notebook(self)
        nb.pack(fill="both", expand=True, padx=10, pady=10)

        self.run_tab  = RunTab(nb, self)
        self.pb_tab   = PBTab(nb, self)
        self.view_tab = ViewTab(nb, self)

        nb.add(self.run_tab,  text="  Add Run  ")
        nb.add(self.pb_tab,   text="  Add Personal Best  ")
        nb.add(self.view_tab, text="  View All  ")

    def refresh_lists(self):
        self.view_tab.refresh()


if __name__ == "__main__":
    init_sneakers_file()
    App().mainloop()
