"""
Running Log – Event Editor
Adds/edits runs and personal bests.
Saves individual JSON files → data/runs/ or data/pbs/
Regenerates data/data.js for running-log.html.
"""

import json
import os
import shutil
import tkinter as tk
from tkinter import filedialog, messagebox, ttk
from datetime import date, datetime
from pathlib import Path

BASE_DIR      = Path(__file__).parent
DATA_DIR      = BASE_DIR / "data"
RUNS_DIR      = DATA_DIR / "runs"
PBS_DIR       = DATA_DIR / "pbs"
PHOTOS_DIR    = DATA_DIR / "photos"
DATA_JS       = DATA_DIR / "data.js"
SNEAKERS_FILE = DATA_DIR / "sneakers.json"

for d in (RUNS_DIR, PBS_DIR, PHOTOS_DIR):
    d.mkdir(parents=True, exist_ok=True)

IMG_EXTS = {".jpg", ".jpeg", ".png", ".gif", ".webp", ".avif"}

# ── JSON helpers ──────────────────────────────────────────────────────────────

def load_all_runs():
    runs = []
    for f in sorted(RUNS_DIR.glob("*.json")):
        try:
            data = json.loads(f.read_text("utf-8-sig"))   # utf-8-sig tolerates a BOM
            data["_path"] = f          # keep source path for reliable deletion
            runs.append(data)
        except Exception as e:
            print(f"Warning: could not read {f.name}: {e}")
    return runs


def load_all_pbs():
    pbs = []
    for f in sorted(PBS_DIR.glob("*.json")):
        try:
            pbs.append(json.loads(f.read_text("utf-8-sig")))
        except Exception as e:
            print(f"Warning: could not read {f.name}: {e}")
    return pbs


def run_filename(run: dict) -> Path:
    return RUNS_DIR / f"{run['date']}.json"


def pb_filename(pb: dict) -> Path:
    slug = pb["distance"].lower().replace(" ", "_").replace("/", "")
    return PBS_DIR / f"{slug}.json"


def save_run(run: dict):
    path = run_filename(run)
    path.write_text(json.dumps(run, ensure_ascii=False, indent=2), "utf-8")


def save_pb(pb: dict):
    path = pb_filename(pb)
    path.write_text(json.dumps(pb, ensure_ascii=False, indent=2), "utf-8")


def _strip_meta(records):
    return [{k: v for k, v in r.items() if not k.startswith("_")} for r in records]


def rebuild_data_js():
    runs = load_all_runs()
    pbs  = load_all_pbs()
    js   = (
        "// Auto-generated by add_new_event.py — do not edit manually\n"
        f"const RUNS_DATA = {json.dumps(_strip_meta(runs), ensure_ascii=False, indent=2)};\n\n"
        f"const PBS_DATA = {json.dumps(_strip_meta(pbs),  ensure_ascii=False, indent=2)};\n"
    )
    DATA_JS.write_text(js, "utf-8")


def copy_photos(src_folder: str, event_key: str) -> list[str]:
    """Copy images from src_folder to data/photos/<event_key>/; return relative paths."""
    if not src_folder:
        return []
    src = Path(src_folder)
    if not src.is_dir():
        return []
    dest = PHOTOS_DIR / event_key
    dest.mkdir(parents=True, exist_ok=True)
    paths = []
    for f in sorted(src.iterdir()):
        if f.suffix.lower() in IMG_EXTS:
            target = dest / f.name
            shutil.copy2(f, target)
            rel = target.relative_to(BASE_DIR).as_posix()
            paths.append(rel)
    return paths


def copy_medal(src_file: str, event_key: str) -> str:
    """Copy a single medal image to data/photos/<event_key>/; return relative path or ''."""
    if not src_file:
        return ""
    src = Path(src_file)
    if not src.is_file() or src.suffix.lower() not in IMG_EXTS:
        return ""
    dest = PHOTOS_DIR / event_key
    dest.mkdir(parents=True, exist_ok=True)
    target = dest / ("medal" + src.suffix.lower())
    shutil.copy2(src, target)
    return target.relative_to(BASE_DIR).as_posix()

# ── Sneakers list ────────────────────────────────────────────────────────────

def load_sneakers() -> list:
    if SNEAKERS_FILE.exists():
        return json.loads(SNEAKERS_FILE.read_text("utf-8-sig"))
    return []


def save_sneakers(names: list):
    SNEAKERS_FILE.write_text(json.dumps(names, ensure_ascii=False, indent=2), "utf-8")


def ensure_sneaker(name: str):
    if not name:
        return
    names = load_sneakers()
    if name not in names:
        names.append(name)
        save_sneakers(names)


def init_sneakers_file():
    if SNEAKERS_FILE.exists():
        return
    names = []
    for r in load_all_runs() + load_all_pbs():
        s = r.get("sneakers", "")
        if s and s not in names:
            names.append(s)
    save_sneakers(names)


# ── GUI ───────────────────────────────────────────────────────────────────────

PAD = {"padx": 8, "pady": 5}
ENTRY_W = 30


def labeled_entry(parent, label, row, default=""):
    tk.Label(parent, text=label, anchor="e", width=16).grid(row=row, column=0, sticky="e", **PAD)
    var = tk.StringVar(value=default)
    tk.Entry(parent, textvariable=var, width=ENTRY_W).grid(row=row, column=1, sticky="ew", **PAD)
    return var


class RunTab(tk.Frame):
    def __init__(self, master, app):
        super().__init__(master)
        self.app = app
        self.columnconfigure(1, weight=1)

        today = date.today().isoformat()

        self.v_date        = labeled_entry(self, "Date (YYYY-MM-DD)", 0, today)
        self.v_race        = labeled_entry(self, "Race name", 1)
        self.v_location    = labeled_entry(self, "Location (EN)", 2)
        self.v_location_be = labeled_entry(self, "Location (BE)", 3)
        self.v_country     = labeled_entry(self, "Country (EN)", 4)
        self.v_country_be  = labeled_entry(self, "Country (BE)", 5)
        self.v_dist        = labeled_entry(self, "Distance (km)", 6)
        self.v_total_time  = labeled_entry(self, "Total time (H:MM:SS)", 7)
        self.v_hr_avg      = labeled_entry(self, "Avg HR (bpm)", 8)
        self.v_hr_max      = labeled_entry(self, "Max HR (bpm)", 9)
        self.v_elevation   = labeled_entry(self, "Elevation (m)", 10, "0")

        tk.Label(self, text="Sneakers", anchor="e", width=16).grid(row=11, column=0, sticky="e", **PAD)
        self.v_sneakers = tk.StringVar()
        self.cb_sneakers_run = ttk.Combobox(self, textvariable=self.v_sneakers, width=ENTRY_W - 2)
        self.cb_sneakers_run['values'] = load_sneakers()
        self.cb_sneakers_run.grid(row=11, column=1, sticky="ew", **PAD)

        self.v_video = labeled_entry(self, "Video link", 12)

        tk.Label(self, text="Medal photo", anchor="e", width=16).grid(row=13, column=0, sticky="e", **PAD)
        medal_frame = tk.Frame(self)
        medal_frame.grid(row=13, column=1, sticky="ew", **PAD)
        medal_frame.columnconfigure(0, weight=1)
        self.v_medal = tk.StringVar()
        tk.Entry(medal_frame, textvariable=self.v_medal).grid(row=0, column=0, sticky="ew")
        tk.Button(medal_frame, text="Browse…", command=self._browse_medal).grid(row=0, column=1, padx=(6, 0))

        # Photos folder row
        tk.Label(self, text="Photos folder", anchor="e", width=16).grid(row=14, column=0, sticky="e", **PAD)
        ph_frame = tk.Frame(self)
        ph_frame.grid(row=14, column=1, sticky="ew", **PAD)
        ph_frame.columnconfigure(0, weight=1)
        self.v_photos = tk.StringVar()
        tk.Entry(ph_frame, textvariable=self.v_photos).grid(row=0, column=0, sticky="ew")
        tk.Button(ph_frame, text="Browse…", command=self._browse).grid(row=0, column=1, padx=(6, 0))

        tk.Button(self, text="💾  Save Run", command=self._save,
                  bg="#e8521b", fg="white", font=("", 11, "bold"),
                  padx=18, pady=6).grid(row=15, column=0, columnspan=2, pady=16)

    def _browse(self):
        folder = filedialog.askdirectory(title="Select photos folder")
        if folder:
            self.v_photos.set(folder)

    def _browse_medal(self):
        path = filedialog.askopenfilename(title="Select medal photo",
            filetypes=[("Images", "*.jpg *.jpeg *.png *.webp *.gif")])
        if path:
            self.v_medal.set(path)

    def _save(self):
        try:
            dist = float(self.v_dist.get().replace(",", "."))
        except ValueError:
            messagebox.showerror("Error", "Distance must be a number.")
            return

        run = {
            "date":        self.v_date.get().strip(),
            "race_name":   self.v_race.get().strip(),
            "location":    self.v_location.get().strip(),
            "location_be": self.v_location_be.get().strip(),
            "country":     self.v_country.get().strip(),
            "country_be":  self.v_country_be.get().strip(),
            "distance_km": dist,
            "total_time":  self.v_total_time.get().strip(),
            "hr_avg":      int(self.v_hr_avg.get() or 0),
            "hr_max":      int(self.v_hr_max.get() or 0),
            "elevation":   int(self.v_elevation.get() or 0),
            "sneakers":    self.v_sneakers.get().strip(),
            "video":       self.v_video.get().strip(),
            "medal":       "",
            "photos":      [],
        }

        event_key = run["date"]
        run["medal"]  = copy_medal(self.v_medal.get(), event_key)
        run["photos"] = copy_photos(self.v_photos.get(), event_key)

        ensure_sneaker(run["sneakers"])
        save_run(run)
        rebuild_data_js()
        self.cb_sneakers_run['values'] = load_sneakers()
        messagebox.showinfo("Saved", f"Run on {run['date']} saved!\n{len(run['photos'])} photo(s) copied.")
        self.app.refresh_lists()


class PBTab(tk.Frame):
    def __init__(self, master, app):
        super().__init__(master)
        self.app = app
        self.columnconfigure(1, weight=1)

        today = date.today().isoformat()

        self.v_distance    = labeled_entry(self, "Distance label", 0, "5 km")
        self.v_distance_km = labeled_entry(self, "Distance (km)", 1)
        self.v_total_time  = labeled_entry(self, "Total time (H:MM:SS)", 2)
        self.v_date        = labeled_entry(self, "Date (YYYY-MM-DD)", 3, today)
        self.v_race        = labeled_entry(self, "Race name", 4)
        self.v_location    = labeled_entry(self, "Location (EN)", 5)
        self.v_location_be = labeled_entry(self, "Location (BE)", 6)
        self.v_country     = labeled_entry(self, "Country (EN)", 7)
        self.v_country_be  = labeled_entry(self, "Country (BE)", 8)
        self.v_hr_avg      = labeled_entry(self, "Avg HR (bpm)", 9)
        self.v_hr_max      = labeled_entry(self, "Max HR (bpm)", 10)

        tk.Label(self, text="Sneakers", anchor="e", width=16).grid(row=11, column=0, sticky="e", **PAD)
        self.v_sneakers = tk.StringVar()
        self.cb_sneakers_pb = ttk.Combobox(self, textvariable=self.v_sneakers, width=ENTRY_W - 2)
        self.cb_sneakers_pb['values'] = load_sneakers()
        self.cb_sneakers_pb.grid(row=11, column=1, sticky="ew", **PAD)

        self.v_video = labeled_entry(self, "Video link", 12)

        tk.Label(self, text="Medal photo", anchor="e", width=16).grid(row=13, column=0, sticky="e", **PAD)
        medal_frame = tk.Frame(self)
        medal_frame.grid(row=13, column=1, sticky="ew", **PAD)
        medal_frame.columnconfigure(0, weight=1)
        self.v_medal = tk.StringVar()
        tk.Entry(medal_frame, textvariable=self.v_medal).grid(row=0, column=0, sticky="ew")
        tk.Button(medal_frame, text="Browse…", command=self._browse_medal).grid(row=0, column=1, padx=(6, 0))

        tk.Label(self, text="Photos folder", anchor="e", width=16).grid(row=14, column=0, sticky="e", **PAD)
        ph_frame = tk.Frame(self)
        ph_frame.grid(row=14, column=1, sticky="ew", **PAD)
        ph_frame.columnconfigure(0, weight=1)
        self.v_photos = tk.StringVar()
        tk.Entry(ph_frame, textvariable=self.v_photos).grid(row=0, column=0, sticky="ew")
        tk.Button(ph_frame, text="Browse…", command=self._browse).grid(row=0, column=1, padx=(6, 0))

        tk.Label(self, text="Previous records", anchor="e", width=16).grid(row=15, column=0, sticky="ne", **PAD)
        self.prev_text = tk.Text(self, height=4, width=ENTRY_W)
        self.prev_text.grid(row=15, column=1, sticky="ew", **PAD)
        tk.Label(self, text="Format: time|date|location\none per line",
                 fg="grey", font=("", 8)).grid(row=16, column=1, sticky="w", padx=8)

        tk.Button(self, text="💾  Save Personal Best", command=self._save,
                  bg="#e8521b", fg="white", font=("", 11, "bold"),
                  padx=18, pady=6).grid(row=17, column=0, columnspan=2, pady=16)

    def _browse(self):
        folder = filedialog.askdirectory(title="Select photos folder")
        if folder:
            self.v_photos.set(folder)

    def _browse_medal(self):
        path = filedialog.askopenfilename(title="Select medal photo",
            filetypes=[("Images", "*.jpg *.jpeg *.png *.webp *.gif")])
        if path:
            self.v_medal.set(path)

    def _parse_previous(self):
        records = []
        for line in self.prev_text.get("1.0", "end").strip().splitlines():
            parts = [p.strip() for p in line.split("|")]
            if len(parts) == 3:
                records.append({"time": parts[0], "date": parts[1], "location": parts[2]})
        return records

    def _save(self):
        try:
            dist_km = float(self.v_distance_km.get().replace(",", "."))
        except ValueError:
            messagebox.showerror("Error", "Distance (km) must be a number.")
            return

        pb = {
            "distance":         self.v_distance.get().strip(),
            "distance_km":      dist_km,
            "total_time":       self.v_total_time.get().strip(),
            "date":             self.v_date.get().strip(),
            "race_name":        self.v_race.get().strip(),
            "location":         self.v_location.get().strip(),
            "location_be":      self.v_location_be.get().strip(),
            "country":          self.v_country.get().strip(),
            "country_be":       self.v_country_be.get().strip(),
            "hr_avg":           int(self.v_hr_avg.get() or 0),
            "hr_max":           int(self.v_hr_max.get() or 0),
            "sneakers":         self.v_sneakers.get().strip(),
            "video":            self.v_video.get().strip(),
            "medal":            "",
            "photos":           [],
            "previous_records": self._parse_previous(),
        }

        event_key = "pb_" + pb["distance"].lower().replace(" ", "_").replace("/", "")
        pb["medal"]  = copy_medal(self.v_medal.get(), event_key)
        pb["photos"] = copy_photos(self.v_photos.get(), event_key)

        ensure_sneaker(pb["sneakers"])
        save_pb(pb)
        rebuild_data_js()
        self.cb_sneakers_pb['values'] = load_sneakers()
        messagebox.showinfo("Saved", f"Personal Best '{pb['distance']}' saved!\n{len(pb['photos'])} photo(s) copied.")
        self.app.refresh_lists()


class EditRunTab(tk.Frame):
    """Select an existing run to edit or delete."""

    def __init__(self, master, app):
        super().__init__(master)
        self.app = app
        self.runs = []
        self.selected_index = None
        self.columnconfigure(1, weight=1)

        # ── Listbox ──────────────────────────────────────────────
        tk.Label(self, text="Select run:", font=("", 9, "bold")).grid(
            row=0, column=0, columnspan=2, sticky="w", padx=8, pady=(8, 2))

        list_frame = tk.Frame(self)
        list_frame.grid(row=1, column=0, columnspan=2, sticky="ew", padx=8, pady=(0, 8))
        list_frame.columnconfigure(0, weight=1)

        self.listbox = tk.Listbox(list_frame, height=5, font=("Courier", 9), exportselection=False)
        sb = tk.Scrollbar(list_frame, command=self.listbox.yview)
        self.listbox.configure(yscrollcommand=sb.set)
        self.listbox.grid(row=0, column=0, sticky="ew")
        sb.grid(row=0, column=1, sticky="ns")
        self.listbox.bind("<<ListboxSelect>>", self._on_select)

        # ── Fields ───────────────────────────────────────────────
        self.v_date        = labeled_entry(self, "Date (YYYY-MM-DD)", 2)
        self.v_race        = labeled_entry(self, "Race name", 3)
        self.v_location    = labeled_entry(self, "Location (EN)", 4)
        self.v_location_be = labeled_entry(self, "Location (BE)", 5)
        self.v_country     = labeled_entry(self, "Country (EN)", 6)
        self.v_country_be  = labeled_entry(self, "Country (BE)", 7)
        self.v_dist        = labeled_entry(self, "Distance (km)", 8)
        self.v_total_time  = labeled_entry(self, "Total time (H:MM:SS)", 9)
        self.v_hr_avg      = labeled_entry(self, "Avg HR (bpm)", 10)
        self.v_hr_max      = labeled_entry(self, "Max HR (bpm)", 11)
        self.v_elevation   = labeled_entry(self, "Elevation (m)", 12)

        tk.Label(self, text="Sneakers", anchor="e", width=16).grid(row=13, column=0, sticky="e", **PAD)
        self.v_sneakers = tk.StringVar()
        self.cb_sneakers = ttk.Combobox(self, textvariable=self.v_sneakers, width=ENTRY_W - 2)
        self.cb_sneakers['values'] = load_sneakers()
        self.cb_sneakers.grid(row=13, column=1, sticky="ew", **PAD)

        self.v_video = labeled_entry(self, "Video link", 14)

        tk.Label(self, text="Medal photo", anchor="e", width=16).grid(row=15, column=0, sticky="e", **PAD)
        medal_frame = tk.Frame(self)
        medal_frame.grid(row=15, column=1, sticky="ew", **PAD)
        medal_frame.columnconfigure(0, weight=1)
        self.v_medal = tk.StringVar()
        tk.Entry(medal_frame, textvariable=self.v_medal).grid(row=0, column=0, sticky="ew")
        tk.Button(medal_frame, text="Browse…", command=self._browse_medal).grid(row=0, column=1, padx=(6, 0))

        tk.Label(self, text="Add photos folder", anchor="e", width=16).grid(row=16, column=0, sticky="e", **PAD)
        ph_frame = tk.Frame(self)
        ph_frame.grid(row=16, column=1, sticky="ew", **PAD)
        ph_frame.columnconfigure(0, weight=1)
        self.v_photos = tk.StringVar()
        tk.Entry(ph_frame, textvariable=self.v_photos).grid(row=0, column=0, sticky="ew")
        tk.Button(ph_frame, text="Browse…", command=self._browse).grid(row=0, column=1, padx=(6, 0))

        tk.Label(self, text="(leave blank to keep\nexisting photos)",
                 fg="grey", font=("", 8)).grid(row=17, column=1, sticky="w", padx=8)

        btn_frame = tk.Frame(self)
        btn_frame.grid(row=18, column=0, columnspan=2, pady=14)
        tk.Button(btn_frame, text="💾  Save Changes", command=self._save,
                  bg="#e8521b", fg="white", font=("", 11, "bold"),
                  padx=14, pady=6).pack(side="left", padx=6)
        tk.Button(btn_frame, text="🗑  Delete Run", command=self._delete,
                  bg="#c0392b", fg="white", font=("", 11, "bold"),
                  padx=14, pady=6).pack(side="left", padx=6)

        self.refresh()

    def refresh(self):
        self.runs = sorted(load_all_runs(), key=lambda x: x["date"], reverse=True)
        self.listbox.delete(0, "end")
        for r in self.runs:
            self.listbox.insert("end", f"{r['date']}  {r['location']}  {r['distance_km']} km")
        self.selected_index = None
        self._clear_fields()

    def _clear_fields(self):
        for v in (self.v_date, self.v_race, self.v_location, self.v_location_be,
                  self.v_country, self.v_country_be, self.v_dist, self.v_total_time,
                  self.v_hr_avg, self.v_hr_max, self.v_elevation, self.v_sneakers, self.v_video,
                  self.v_medal, self.v_photos):
            v.set("")

    def _on_select(self, _event):
        sel = self.listbox.curselection()
        if not sel:
            return
        self.selected_index = sel[0]
        r = self.runs[self.selected_index]
        self.v_date.set(r.get("date", ""))
        self.v_race.set(r.get("race_name", ""))
        self.v_location.set(r.get("location", ""))
        self.v_location_be.set(r.get("location_be", ""))
        self.v_country.set(r.get("country", ""))
        self.v_country_be.set(r.get("country_be", ""))
        self.v_dist.set(str(r.get("distance_km", "")))
        self.v_total_time.set(r.get("total_time", ""))
        self.v_hr_avg.set(str(r.get("hr_avg", "")))
        self.v_hr_max.set(str(r.get("hr_max", "")))
        self.v_elevation.set(str(r.get("elevation", 0)))
        self.v_sneakers.set(r.get("sneakers", ""))
        self.v_video.set(r.get("video", ""))
        self.v_medal.set(r.get("medal", ""))
        self.v_photos.set("")

    def _browse(self):
        folder = filedialog.askdirectory(title="Select photos folder")
        if folder:
            self.v_photos.set(folder)

    def _browse_medal(self):
        path = filedialog.askopenfilename(title="Select medal photo",
            filetypes=[("Images", "*.jpg *.jpeg *.png *.webp *.gif")])
        if path:
            self.v_medal.set(path)

    def _save(self):
        if self.selected_index is None:
            messagebox.showwarning("No selection", "Select a run from the list first.")
            return
        old_run = self.runs[self.selected_index]
        try:
            dist = float(self.v_dist.get().replace(",", "."))
        except ValueError:
            messagebox.showerror("Error", "Distance must be a number.")
            return

        run = {
            "date":        self.v_date.get().strip(),
            "race_name":   self.v_race.get().strip(),
            "location":    self.v_location.get().strip(),
            "location_be": self.v_location_be.get().strip(),
            "country":     self.v_country.get().strip(),
            "country_be":  self.v_country_be.get().strip(),
            "distance_km": dist,
            "total_time":  self.v_total_time.get().strip(),
            "hr_avg":      int(self.v_hr_avg.get() or 0),
            "hr_max":      int(self.v_hr_max.get() or 0),
            "elevation":   int(self.v_elevation.get() or 0),
            "sneakers":    self.v_sneakers.get().strip(),
            "video":       self.v_video.get().strip(),
            "medal":       old_run.get("medal", ""),
            "photos":      old_run.get("photos", []),
        }

        # Always delete the original file (path may differ from run_filename if old naming format)
        old_path = old_run.get("_path") or run_filename(old_run)
        new_path = run_filename(run)
        if old_path.exists() and old_path != new_path:
            old_path.unlink()
        elif old_path.exists() and old_path == new_path:
            old_path.unlink()  # will be rewritten by save_run below

        # Update medal if a new file was specified
        new_medal = self.v_medal.get().strip()
        if new_medal:
            run["medal"] = copy_medal(new_medal, run["date"])

        # Add new photos if a folder was specified
        new_folder = self.v_photos.get().strip()
        if new_folder:
            new_photos = copy_photos(new_folder, run["date"])
            run["photos"] = run["photos"] + new_photos

        ensure_sneaker(run["sneakers"])
        save_run(run)
        rebuild_data_js()
        self.cb_sneakers['values'] = load_sneakers()
        messagebox.showinfo("Saved", f"Run on {run['date']} updated.")
        self.app.refresh_lists()

    def _delete(self):
        if self.selected_index is None:
            messagebox.showwarning("No selection", "Select a run from the list first.")
            return
        run = self.runs[self.selected_index]
        if not messagebox.askyesno("Confirm delete",
                                   f"Delete run {run['date']} – {run['location']}?\n"
                                   "This cannot be undone."):
            return
        path = run_filename(run)
        if path.exists():
            path.unlink()
        rebuild_data_js()
        messagebox.showinfo("Deleted", f"Run {run['date']} deleted.")
        self.app.refresh_lists()


class EditPBTab(tk.Frame):
    """Select an existing personal best to edit or delete."""

    def __init__(self, master, app):
        super().__init__(master)
        self.app = app
        self.pbs = []
        self.selected_index = None
        self.columnconfigure(1, weight=1)

        tk.Label(self, text="Select personal best:", font=("", 9, "bold")).grid(
            row=0, column=0, columnspan=2, sticky="w", padx=8, pady=(8, 2))

        list_frame = tk.Frame(self)
        list_frame.grid(row=1, column=0, columnspan=2, sticky="ew", padx=8, pady=(0, 8))
        list_frame.columnconfigure(0, weight=1)

        self.listbox = tk.Listbox(list_frame, height=4, font=("Courier", 9), exportselection=False)
        sb = tk.Scrollbar(list_frame, command=self.listbox.yview)
        self.listbox.configure(yscrollcommand=sb.set)
        self.listbox.grid(row=0, column=0, sticky="ew")
        sb.grid(row=0, column=1, sticky="ns")
        self.listbox.bind("<<ListboxSelect>>", self._on_select)

        self.v_distance    = labeled_entry(self, "Distance label", 2)
        self.v_distance_km = labeled_entry(self, "Distance (km)", 3)
        self.v_total_time  = labeled_entry(self, "Total time (H:MM:SS)", 4)
        self.v_date        = labeled_entry(self, "Date (YYYY-MM-DD)", 5)
        self.v_race        = labeled_entry(self, "Race name", 6)
        self.v_location    = labeled_entry(self, "Location (EN)", 7)
        self.v_location_be = labeled_entry(self, "Location (BE)", 8)
        self.v_country     = labeled_entry(self, "Country (EN)", 9)
        self.v_country_be  = labeled_entry(self, "Country (BE)", 10)
        self.v_hr_avg      = labeled_entry(self, "Avg HR (bpm)", 11)
        self.v_hr_max      = labeled_entry(self, "Max HR (bpm)", 12)

        tk.Label(self, text="Sneakers", anchor="e", width=16).grid(row=13, column=0, sticky="e", **PAD)
        self.v_sneakers = tk.StringVar()
        self.cb_sneakers = ttk.Combobox(self, textvariable=self.v_sneakers, width=ENTRY_W - 2)
        self.cb_sneakers['values'] = load_sneakers()
        self.cb_sneakers.grid(row=13, column=1, sticky="ew", **PAD)

        self.v_video = labeled_entry(self, "Video link", 14)

        tk.Label(self, text="Medal photo", anchor="e", width=16).grid(row=15, column=0, sticky="e", **PAD)
        medal_frame = tk.Frame(self)
        medal_frame.grid(row=15, column=1, sticky="ew", **PAD)
        medal_frame.columnconfigure(0, weight=1)
        self.v_medal = tk.StringVar()
        tk.Entry(medal_frame, textvariable=self.v_medal).grid(row=0, column=0, sticky="ew")
        tk.Button(medal_frame, text="Browse…", command=self._browse_medal).grid(row=0, column=1, padx=(6, 0))

        tk.Label(self, text="Add photos folder", anchor="e", width=16).grid(row=16, column=0, sticky="e", **PAD)
        ph_frame = tk.Frame(self)
        ph_frame.grid(row=16, column=1, sticky="ew", **PAD)
        ph_frame.columnconfigure(0, weight=1)
        self.v_photos = tk.StringVar()
        tk.Entry(ph_frame, textvariable=self.v_photos).grid(row=0, column=0, sticky="ew")
        tk.Button(ph_frame, text="Browse…", command=self._browse).grid(row=0, column=1, padx=(6, 0))

        tk.Label(self, text="Previous records", anchor="e", width=16).grid(row=17, column=0, sticky="ne", **PAD)
        self.prev_text = tk.Text(self, height=4, width=ENTRY_W)
        self.prev_text.grid(row=17, column=1, sticky="ew", **PAD)
        tk.Label(self, text="Format: time|date|location\none per line",
                 fg="grey", font=("", 8)).grid(row=18, column=1, sticky="w", padx=8)

        btn_frame = tk.Frame(self)
        btn_frame.grid(row=19, column=0, columnspan=2, pady=14)
        tk.Button(btn_frame, text="💾  Save Changes", command=self._save,
                  bg="#e8521b", fg="white", font=("", 11, "bold"),
                  padx=14, pady=6).pack(side="left", padx=6)
        tk.Button(btn_frame, text="🗑  Delete PB", command=self._delete,
                  bg="#c0392b", fg="white", font=("", 11, "bold"),
                  padx=14, pady=6).pack(side="left", padx=6)

        self.refresh()

    def refresh(self):
        self.pbs = load_all_pbs()
        self.listbox.delete(0, "end")
        for pb in self.pbs:
            self.listbox.insert("end", f"{pb['distance']}  {pb['total_time']}  {pb['date']}")
        self.selected_index = None
        self._clear_fields()

    def _clear_fields(self):
        for v in (self.v_distance, self.v_distance_km, self.v_total_time, self.v_date,
                  self.v_race, self.v_location, self.v_location_be, self.v_country,
                  self.v_country_be, self.v_hr_avg, self.v_hr_max,
                  self.v_sneakers, self.v_video, self.v_medal, self.v_photos):
            v.set("")
        self.prev_text.delete("1.0", "end")

    def _on_select(self, _event):
        sel = self.listbox.curselection()
        if not sel:
            return
        self.selected_index = sel[0]
        pb = self.pbs[self.selected_index]
        self.v_distance.set(pb.get("distance", ""))
        self.v_distance_km.set(str(pb.get("distance_km", "")))
        self.v_total_time.set(pb.get("total_time", ""))
        self.v_date.set(pb.get("date", ""))
        self.v_race.set(pb.get("race_name", ""))
        self.v_location.set(pb.get("location", ""))
        self.v_location_be.set(pb.get("location_be", ""))
        self.v_country.set(pb.get("country", ""))
        self.v_country_be.set(pb.get("country_be", ""))
        self.v_hr_avg.set(str(pb.get("hr_avg", "")))
        self.v_hr_max.set(str(pb.get("hr_max", "")))
        self.v_sneakers.set(pb.get("sneakers", ""))
        self.v_video.set(pb.get("video", ""))
        self.v_medal.set(pb.get("medal", ""))
        self.v_photos.set("")
        self.prev_text.delete("1.0", "end")
        for r in pb.get("previous_records", []):
            self.prev_text.insert("end", f"{r['time']}|{r['date']}|{r['location']}\n")

    def _browse(self):
        folder = filedialog.askdirectory(title="Select photos folder")
        if folder:
            self.v_photos.set(folder)

    def _browse_medal(self):
        path = filedialog.askopenfilename(title="Select medal photo",
            filetypes=[("Images", "*.jpg *.jpeg *.png *.webp *.gif")])
        if path:
            self.v_medal.set(path)

    def _parse_previous(self):
        records = []
        for line in self.prev_text.get("1.0", "end").strip().splitlines():
            parts = [p.strip() for p in line.split("|")]
            if len(parts) == 3:
                records.append({"time": parts[0], "date": parts[1], "location": parts[2]})
        return records

    def _save(self):
        if self.selected_index is None:
            messagebox.showwarning("No selection", "Select a personal best from the list first.")
            return
        old_pb = self.pbs[self.selected_index]
        try:
            dist_km = float(self.v_distance_km.get().replace(",", "."))
        except ValueError:
            messagebox.showerror("Error", "Distance (km) must be a number.")
            return

        pb = {
            "distance":         self.v_distance.get().strip(),
            "distance_km":      dist_km,
            "total_time":       self.v_total_time.get().strip(),
            "date":             self.v_date.get().strip(),
            "race_name":        self.v_race.get().strip(),
            "location":         self.v_location.get().strip(),
            "location_be":      self.v_location_be.get().strip(),
            "country":          self.v_country.get().strip(),
            "country_be":       self.v_country_be.get().strip(),
            "hr_avg":           int(self.v_hr_avg.get() or 0),
            "hr_max":           int(self.v_hr_max.get() or 0),
            "sneakers":         self.v_sneakers.get().strip(),
            "video":            self.v_video.get().strip(),
            "medal":            old_pb.get("medal", ""),
            "photos":           old_pb.get("photos", []),
            "previous_records": self._parse_previous(),
        }

        old_path = pb_filename(old_pb)
        new_path = pb_filename(pb)
        if old_path != new_path and old_path.exists():
            old_path.unlink()

        event_key = "pb_" + pb["distance"].lower().replace(" ", "_").replace("/", "")

        new_medal = self.v_medal.get().strip()
        if new_medal and new_medal != old_pb.get("medal", ""):
            pb["medal"] = copy_medal(new_medal, event_key)

        new_folder = self.v_photos.get().strip()
        if new_folder:
            new_photos = copy_photos(new_folder, event_key)
            pb["photos"] = pb["photos"] + new_photos

        ensure_sneaker(pb["sneakers"])
        save_pb(pb)
        rebuild_data_js()
        self.cb_sneakers['values'] = load_sneakers()
        messagebox.showinfo("Saved", f"Personal Best '{pb['distance']}' updated.")
        self.app.refresh_lists()

    def _delete(self):
        if self.selected_index is None:
            messagebox.showwarning("No selection", "Select a personal best from the list first.")
            return
        pb = self.pbs[self.selected_index]
        if not messagebox.askyesno("Confirm delete",
                                   f"Delete PB '{pb['distance']}' ({pb['total_time']})?\n"
                                   "This cannot be undone."):
            return
        path = pb_filename(pb)
        if path.exists():
            path.unlink()
        rebuild_data_js()
        messagebox.showinfo("Deleted", f"Personal Best '{pb['distance']}' deleted.")
        self.app.refresh_lists()


class ViewTab(tk.Frame):
    """Simple read-only list of existing events."""

    def __init__(self, master, app):
        super().__init__(master)
        self.app = app
        self.columnconfigure(0, weight=1)
        self.rowconfigure(1, weight=1)

        tk.Label(self, text="Existing events (read-only)", font=("", 10, "bold")).grid(
            row=0, column=0, sticky="w", padx=8, pady=(8, 4))

        self.text = tk.Text(self, state="disabled", wrap="none", font=("Courier", 9))
        sb = tk.Scrollbar(self, command=self.text.yview)
        self.text.configure(yscrollcommand=sb.set)
        self.text.grid(row=1, column=0, sticky="nsew", padx=(8, 0), pady=4)
        sb.grid(row=1, column=1, sticky="ns", pady=4)

        tk.Button(self, text="↺  Refresh", command=self.refresh).grid(
            row=2, column=0, columnspan=2, pady=8)

        self.refresh()

    def refresh(self):
        lines = ["═══ RUNS ═══"]
        for r in sorted(load_all_runs(), key=lambda x: x["date"], reverse=True):
            lines.append(f"  {r['date']}  {r['location']}  {r['distance_km']} km  {r['total_time']}")
        lines += ["", "═══ PERSONAL BESTS ═══"]
        for pb in load_all_pbs():
            lines.append(f"  {pb['distance']}  {pb['total_time']}  {pb['date']}  {pb['location']}")
        content = "\n".join(lines)

        self.text.configure(state="normal")
        self.text.delete("1.0", "end")
        self.text.insert("end", content)
        self.text.configure(state="disabled")


class App(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title("Running Log – Event Manager")
        self.resizable(True, True)
        self.minsize(520, 520)

        nb = ttk.Notebook(self)
        nb.pack(fill="both", expand=True, padx=10, pady=10)

        self.run_tab      = RunTab(nb, self)
        self.pb_tab       = PBTab(nb, self)
        self.edit_run_tab = EditRunTab(nb, self)
        self.edit_pb_tab  = EditPBTab(nb, self)
        self.view_tab     = ViewTab(nb, self)

        nb.add(self.run_tab,      text="  Add Run  ")
        nb.add(self.pb_tab,       text="  Add Personal Best  ")
        nb.add(self.edit_run_tab, text="  Edit Run  ")
        nb.add(self.edit_pb_tab,  text="  Edit Personal Best  ")
        nb.add(self.view_tab,     text="  View All  ")

    def refresh_lists(self):
        self.edit_run_tab.refresh()
        self.edit_pb_tab.refresh()
        self.view_tab.refresh()


if __name__ == "__main__":
    init_sneakers_file()
    App().mainloop()
