"""
Process Garmin activity CSV files from data/activities/ folder.
Merges all CSVs; for duplicate activity datetimes, the latest-modified file wins.
Filters to running activity types only.
Outputs data/activities.js (ACTIVITIES_DATA).

Usage:
    python process_activities.py
    (or double-click process_activities.bat)

Drop exported Garmin CSV files into data/activities/ and re-run.
"""

import csv
import json
from pathlib import Path

BASE_DIR       = Path(__file__).parent
ACTIVITIES_DIR = BASE_DIR / "data" / "activities"
OUTPUT_JS      = BASE_DIR / "data" / "activities.js"

RUNNING_TYPES = {
    "Running", "Trail Running", "Track Running", "Obstacle Course Racing",
    "Indoor Running", "Street Running", "Treadmill Running",
    "Ultra Running", "Virtual Running",
}


def parse_num(s: str, default: float = 0.0) -> float:
    try:
        return float(str(s).strip().replace(",", ""))
    except ValueError:
        return default


def parse_elevation(s: str) -> int:
    s = str(s).strip().replace(",", "")
    try:
        return max(0, int(float(s)))
    except ValueError:
        return 0


def process():
    ACTIVITIES_DIR.mkdir(parents=True, exist_ok=True)

    # Sort by modification time ascending — later file's rows overwrite earlier ones
    csv_files = sorted(ACTIVITIES_DIR.glob("*.csv"), key=lambda f: f.stat().st_mtime)

    if not csv_files:
        print("No CSV files found in", ACTIVITIES_DIR)
        OUTPUT_JS.write_text(
            "// Auto-generated by process_activities.py — do not edit manually\n"
            "const ACTIVITIES_DATA = [];\n",
            encoding="utf-8",
        )
        return

    records: dict[str, dict] = {}  # key: full datetime string → record

    for path in csv_files:
        try:
            with open(path, encoding="utf-8-sig", newline="") as f:
                reader = csv.DictReader(f)
                for row in reader:
                    atype = row.get("Activity Type", "").strip()
                    if atype not in RUNNING_TYPES:
                        continue
                    dt = row.get("Date", "").strip()
                    if not dt:
                        continue
                    records[dt] = {
                        "type":        atype,
                        "date":        dt[:10],
                        "datetime":    dt,
                        "distance_km": round(parse_num(row.get("Distance", "0")), 2),
                        "time":        row.get("Time", "").strip(),
                        "elevation":   parse_elevation(row.get("Total Ascent", "0")),
                    }
        except Exception as e:
            print(f"Warning: could not read {path.name}: {e}")

    result = sorted(records.values(), key=lambda r: r["datetime"], reverse=True)

    js = (
        "// Auto-generated by process_activities.py — do not edit manually\n"
        f"const ACTIVITIES_DATA = {json.dumps(result, ensure_ascii=False, indent=2)};\n"
    )
    OUTPUT_JS.write_text(js, encoding="utf-8")
    print(f"Processed {len(csv_files)} file(s) → {len(result)} running activities → {OUTPUT_JS.name}")


if __name__ == "__main__":
    process()
